[package]
name = "processpriorityenforcer"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = { version = "0.6.5", features = ["track-caller"], default-features = false }
globset = "0.4.20"
latches = "0.2.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
] }
wmi = "0.18.4"

[target.'cfg(windows)'.build-dependencies]
chrono = { version = "0.4.45", features = ["now"], default-features = false }
winresource = { version = "0.1.31", default-features = false }

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
strip = true
